pdoc \
uHDR.py \
guiQt/controller.py \
guiQt/model.py \
guiQt/view.py \
guiQt/view.useCase.py \
guiQt/thread.py \
hdrCore/metadata.py \
hdrCore/image.py \
hdrCore/aesthetics.py \
hdrCore/coreC.py \
hdrCore/net.py \
hdrCore/numbafun.py \
hdrCore/processing.py \
hdrCore/quality.py \
hdrCore/srgb.py \
hdrCore/utils.py \
preferences/preferences.py \
-o docs/
